---
- name: Prepare remote servers
  hosts: all
  remote_user: wooolf
  become: true

  tasks:
    - name: Install prerquisists
      include_role:
        name: install_software

    - name: Prepare master node
      include_role:
        name: prepare_k8s_master
      when: "'master' in inventory_hostname"
      tags:
        - client_tools
