---
# tasks file for prepare_k8s_etcd

- name: etcd
  block:
    - name: Download etcd binaries
      ansible.builtin.get_url:
        url: "https://github.com/etcd-io/etcd/releases/download/v3.4.15/etcd-v3.4.15-linux-amd64.tar.gz"
        dest: "/home/{{ ansible_user }}/"
        mode: 0777

    - name: Unarchive
      ansible.builtin.unarchive:
        remote_src: true
        src: /home/{{ ansible_user }}/etcd-v3.4.15-linux-amd64.tar.gz
        dest: /home/{{ ansible_user }}/

    - name: Copy etcd to /usr/local/bin
      copy:
        remote_src: True
        src: "/home/{{ ansible_user }}/etcd-v3.4.15-linux-amd64/{{ item }}"
        dest: /usr/local/bin/
        mode: 0755
      loop:
        - etcd
        - etcdctl

    - name: Configure etcd server
      ansible.builtin.file:
        state: directory
        path: "{{ item }}"
        owner: root
        group: root
        mode: "0700"
      loop:
        - /etc/etcd
        - /var/lib/etcd

    - name: Copy keys
      copy:
        src: "/home/{{ ansible_user }}/certs/{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: 0700
        remote_src: True
      register: transfer_keys
      loop:
        - { src: ca.pem, dest: /etc/etcd/ }
        - { src: kubernetes-key.pem, dest: /etc/etcd/ }
        - { src: kubernetes.pem, dest: /etc/etcd/ }

    - name: Copy script
      copy:
        src: deploy_etcd.sh
        dest: /home/{{ ansible_user }}/
        mode: 0777
      register: copy_etcd_script
      notify:
        - "Run etcd config"

    - name: Debug copy script
      debug:
        msg: "Show details: {{ copy_etcd_script }}"

    - name: Enable etcd
      ansible.builtin.systemd:
        name: etcd.service
        daemon_reload: yes
        state: started
        enabled: true
  tags:
    - etcd
